name: CI/CD - Desenvolvimento

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Job de verificação de qualidade do código
  code-quality:
    name: Qualidade do Código
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: logoshub-app/package-lock.json
        
    - name: Instalar dependências
      run: |
        cd logoshub-app
        npm ci
        
    - name: Verificar formatação do código
      run: |
        cd logoshub-app
        npm run format:check
        
    - name: Executar linting
      run: |
        cd logoshub-app
        npm run lint
        
  # Job de testes
  test:
    name: Testes
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: logoshub-app/package-lock.json
        
    - name: Instalar dependências
      run: |
        cd logoshub-app
        npm ci
        
    - name: Executar testes
      run: |
        cd logoshub-app
        npm run test:ci
        
    - name: Upload cobertura de testes
      uses: codecov/codecov-action@v3
      with:
        file: logoshub-app/coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        
  # Job de build
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [code-quality, test]
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: logoshub-app/package-lock.json
        
    - name: Instalar dependências (produção)
      run: |
        cd logoshub-app
        npm ci --omit=dev --legacy-peer-deps
        
    - name: Build de produção
      run: |
        cd logoshub-app
        npm run build:prod
        
    - name: Upload artefatos de build
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: logoshub-app/dist/
        retention-days: 7
        
  # Job de deploy para desenvolvimento (apenas em push para develop)
  deploy-dev:
    name: Deploy para Desenvolvimento
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: logoshub-app/package-lock.json
        
    - name: Instalar dependências (produção)
      run: |
        cd logoshub-app
        npm ci --omit=dev --legacy-peer-deps
        
    - name: Download artefatos de build
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: logoshub-app/dist/
        
    - name: Deploy para ambiente de desenvolvimento
      run: |
        echo "Deploy para ambiente de desenvolvimento"
        # Aqui você pode adicionar comandos específicos para seu ambiente
        # Por exemplo: Firebase Hosting, Vercel, Netlify, etc.
        
    - name: Notificar deploy
      run: |
        echo "✅ Deploy para desenvolvimento concluído com sucesso!"
        echo "🌐 URL: https://dev.logoshub.com"
        
  # Job de verificação de segurança
  security:
    name: Verificação de Segurança
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: logoshub-app/package-lock.json
        
    - name: Instalar dependências
      run: |
        cd logoshub-app
        npm ci
        
    - name: Verificar vulnerabilidades
      run: |
        cd logoshub-app
        npm audit --audit-level=moderate
        
    - name: Verificar licenças
      run: |
        cd logoshub-app
        npx license-checker --summary --onlyAllow "MIT;ISC;Apache-2.0;BSD-2-Clause;BSD-3-Clause"
