name: Deploy de Produção

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  # Build otimizado para produção
  build-production:
    name: Build de Produção
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: logoshub-app/package-lock.json
        
    - name: Instalar dependências (produção)
      run: |
        cd logoshub-app
        npm ci --omit=dev
        
    - name: Build de produção
      run: |
        cd logoshub-app
        npm run build:prod
        
    - name: Upload artefatos de produção
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: logoshub-app/dist/
        retention-days: 30
        
  # Deploy para produção
  deploy-production:
    name: Deploy para Produção
    runs-on: ubuntu-latest
    needs: build-production
    environment: production
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: logoshub-app/package-lock.json
        
    - name: Instalar dependências (produção)
      run: |
        cd logoshub-app
        npm ci --omit=dev
        
    - name: Download artefatos de produção
      uses: actions/download-artifact@v4
      with:
        name: production-build
        path: logoshub-app/dist/
        
    - name: Deploy para produção
      run: |
        echo "🚀 Iniciando deploy para produção..."
        # Aqui você pode adicionar comandos específicos para seu ambiente de produção
        # Por exemplo: Firebase Hosting, Vercel, Netlify, etc.
        
    - name: Notificar deploy
      run: |
        echo "✅ Deploy para produção concluído com sucesso!"
        echo "🌐 URL: https://logoshub.com"
        
    - name: Criar release tag
      if: github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "v$(date +%Y%m%d-%H%M%S)" -m "Deploy automático para produção"
        git push origin --tags
